use serde::Deserialize;
use std::{env, fs, path::Path};

#[derive(Debug, Deserialize)]
struct MetadataSource {
    opcodes: Vec<Family>,
    cb_opcodes: Vec<Family>,
}

#[derive(Debug, Deserialize)]
struct Family {
    family: String,
}

fn main() {
    println!("cargo:rerun-if-changed=opcodes.toml");
    let source = fs::read_to_string("opcodes.toml").expect("read opcodes.toml");
    let source: MetadataSource = toml::from_str(&source).expect("parse opcodes.toml");
    assert!(source.opcodes.iter().any(|f| f.family == "base"));
    assert!(source.cb_opcodes.iter().any(|f| f.family == "cb_bitops"));

    let mut out = String::new();
    out.push_str("// @generated by core/build.rs from core/opcodes.toml\n");
    out.push_str("pub const OPCODES: [Option<OpcodeMetadata>; 256] = [\n");
    for opcode in 0u16..=0xff {
        match metadata_for(opcode as u8) {
            Some(meta) => out.push_str(&format!("    Some({meta}), // 0x{opcode:02X}\n")),
            None => out.push_str(&format!("    None, // 0x{opcode:02X}\n")),
        }
    }
    out.push_str("];\n\n");
    out.push_str("pub const CB_OPCODES: [OpcodeMetadata; 256] = [\n");
    for opcode in 0u16..=0xff {
        out.push_str(&format!(
            "    {}, // CB 0x{opcode:02X}\n",
            cb_metadata_for(opcode as u8)
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("opcode_tables.rs"), out).expect("write opcode_tables.rs");
}

fn meta(
    opcode: u8,
    instruction: &str,
    op8: Option<String>,
    op16: Option<String>,
    cond: Option<String>,
    cycles: &str,
) -> String {
    format!(
        "OpcodeMetadata {{ opcode: 0x{opcode:02X}, instruction: {instruction}, operand8: {}, operand16: {}, condition: {}, cycles: {cycles} }}",
        option(op8), option(op16), option(cond)
    )
}

fn option(value: Option<String>) -> String {
    value.map_or_else(|| "None".to_string(), |v| format!("Some({v})"))
}
fn r8(i: u8) -> String {
    format!("Operand8::R8({i})")
}
fn r16(i: u8) -> String {
    format!("Operand16::R16({i})")
}
fn r16stk(i: u8) -> String {
    format!("Operand16::StackR16({i})")
}
fn cond(i: u8) -> String {
    format!("Condition::from_index({i})")
}
fn fixed(n: u32) -> String {
    format!("CycleCost::Fixed({n})")
}
fn branch(t: u32, nt: u32) -> String {
    format!("CycleCost::Branch {{ taken: {t}, not_taken: {nt} }}")
}
fn mem(reg: u32, mem: u32) -> String {
    format!("CycleCost::MemoryOperand {{ register: {reg}, memory: {mem} }}")
}
fn ld_rr(dst_mem: bool, src_mem: bool) -> String {
    if dst_mem || src_mem {
        fixed(8)
    } else {
        fixed(4)
    }
}

fn metadata_for(opcode: u8) -> Option<String> {
    let m = match opcode {
        0x00 => meta(opcode, "Instruction::Nop", None, None, None, &fixed(4)),
        0x07 => meta(opcode, "Instruction::Rlca", None, None, None, &fixed(4)),
        0x08 => meta(
            opcode,
            "Instruction::LdSpToImm16Addr",
            None,
            Some("Operand16::Imm16".into()),
            None,
            &fixed(20),
        ),
        0x02 | 0x12 => meta(
            opcode,
            "Instruction::LdMemFromA",
            None,
            Some(r16((opcode >> 4) & 3)),
            None,
            &fixed(8),
        ),
        0x03 | 0x13 | 0x23 | 0x33 => meta(
            opcode,
            "Instruction::Inc16",
            None,
            Some(r16((opcode >> 4) & 3)),
            None,
            &fixed(8),
        ),
        0x01 | 0x11 | 0x21 | 0x31 => meta(
            opcode,
            "Instruction::Ld16Imm",
            None,
            Some(r16((opcode >> 4) & 3)),
            None,
            &fixed(12),
        ),
        0x0A | 0x1A => meta(
            opcode,
            "Instruction::LdAFromMem",
            None,
            Some(r16((opcode >> 4) & 3)),
            None,
            &fixed(8),
        ),
        0x0B | 0x1B | 0x2B | 0x3B => meta(
            opcode,
            "Instruction::Dec16",
            None,
            Some(r16((opcode >> 4) & 3)),
            None,
            &fixed(8),
        ),
        0x09 | 0x19 | 0x29 | 0x39 => meta(
            opcode,
            "Instruction::AddHl",
            None,
            Some(r16((opcode >> 4) & 3)),
            None,
            &fixed(8),
        ),
        0x22 => meta(
            opcode,
            "Instruction::LdHliFromA",
            None,
            None,
            None,
            &fixed(8),
        ),
        0x2A => meta(
            opcode,
            "Instruction::LdAFromHli",
            None,
            None,
            None,
            &fixed(8),
        ),
        0x32 => meta(
            opcode,
            "Instruction::LdHldFromA",
            None,
            None,
            None,
            &fixed(8),
        ),
        0x3A => meta(
            opcode,
            "Instruction::LdAFromHld",
            None,
            None,
            None,
            &fixed(8),
        ),
        0x0F => meta(opcode, "Instruction::Rrca", None, None, None, &fixed(4)),
        0x10 => meta(
            opcode,
            "Instruction::Stop",
            Some("Operand8::Imm8".into()),
            None,
            None,
            &fixed(4),
        ),
        0x18 => meta(
            opcode,
            "Instruction::Jr",
            Some("Operand8::Relative".into()),
            None,
            None,
            &fixed(12),
        ),
        0x20 | 0x28 | 0x30 | 0x38 => meta(
            opcode,
            "Instruction::JrCond",
            Some("Operand8::Relative".into()),
            None,
            Some(cond((opcode >> 3) & 3)),
            &branch(12, 8),
        ),
        0x17 => meta(opcode, "Instruction::Rla", None, None, None, &fixed(4)),
        0x1F => meta(opcode, "Instruction::Rra", None, None, None, &fixed(4)),
        0x27 => meta(opcode, "Instruction::Daa", None, None, None, &fixed(4)),
        0x2F => meta(opcode, "Instruction::Cpl", None, None, None, &fixed(4)),
        0x37 => meta(opcode, "Instruction::Scf", None, None, None, &fixed(4)),
        0x3F => meta(opcode, "Instruction::Ccf", None, None, None, &fixed(4)),
        0x06 | 0x0E | 0x16 | 0x1E | 0x26 | 0x2E | 0x36 | 0x3E => meta(
            opcode,
            "Instruction::Ld8Imm",
            Some(r8((opcode >> 3) & 7)),
            None,
            None,
            &mem(8, 12),
        ),
        0x04 | 0x0C | 0x14 | 0x1C | 0x24 | 0x2C | 0x34 | 0x3C => meta(
            opcode,
            "Instruction::Inc8",
            Some(r8((opcode >> 3) & 7)),
            None,
            None,
            &mem(4, 12),
        ),
        0x05 | 0x0D | 0x15 | 0x1D | 0x25 | 0x2D | 0x35 | 0x3D => meta(
            opcode,
            "Instruction::Dec8",
            Some(r8((opcode >> 3) & 7)),
            None,
            None,
            &mem(4, 12),
        ),
        0x40..=0x7F => {
            if opcode == 0x76 {
                meta(opcode, "Instruction::Halt", None, None, None, &fixed(4))
            } else {
                meta(
                    opcode,
                    "Instruction::Ld8",
                    Some(r8((opcode >> 3) & 7)),
                    Some(format!("Operand16::R8Source({})", opcode & 7)),
                    None,
                    &ld_rr(((opcode >> 3) & 7) == 6, (opcode & 7) == 6),
                )
            }
        }
        0x80..=0xBF => meta(
            opcode,
            "Instruction::Alu8",
            Some(r8(opcode & 7)),
            None,
            None,
            &mem(4, 8),
        ),
        0xC6 | 0xCE | 0xD6 | 0xDE | 0xE6 | 0xEE | 0xF6 | 0xFE => meta(
            opcode,
            "Instruction::AluImm8",
            Some("Operand8::Imm8".into()),
            None,
            None,
            &fixed(8),
        ),
        0xC0 | 0xC8 | 0xD0 | 0xD8 => meta(
            opcode,
            "Instruction::RetCond",
            None,
            None,
            Some(cond((opcode >> 3) & 3)),
            &branch(20, 8),
        ),
        0xC1 | 0xD1 | 0xE1 | 0xF1 => meta(
            opcode,
            "Instruction::Pop",
            None,
            Some(r16stk((opcode >> 4) & 3)),
            None,
            &fixed(12),
        ),
        0xC2 | 0xCA | 0xD2 | 0xDA => meta(
            opcode,
            "Instruction::JpCond",
            None,
            Some("Operand16::Imm16".into()),
            Some(cond((opcode >> 3) & 3)),
            &branch(16, 12),
        ),
        0xC3 => meta(
            opcode,
            "Instruction::Jp",
            None,
            Some("Operand16::Imm16".into()),
            None,
            &fixed(16),
        ),
        0xC4 | 0xCC | 0xD4 | 0xDC => meta(
            opcode,
            "Instruction::CallCond",
            None,
            Some("Operand16::Imm16".into()),
            Some(cond((opcode >> 3) & 3)),
            &branch(24, 12),
        ),
        0xC5 | 0xD5 | 0xE5 | 0xF5 => meta(
            opcode,
            "Instruction::Push",
            None,
            Some(r16stk((opcode >> 4) & 3)),
            None,
            &fixed(16),
        ),
        0xC7 | 0xCF | 0xD7 | 0xDF | 0xE7 | 0xEF | 0xF7 | 0xFF => meta(
            opcode,
            "Instruction::Rst",
            Some(format!("Operand8::Vector(0x{:02X})", opcode & 0x38)),
            None,
            None,
            &fixed(16),
        ),
        0xCB => meta(
            opcode,
            "Instruction::PrefixCb",
            Some("Operand8::CbOpcode".into()),
            None,
            None,
            &fixed(0),
        ),
        0xC9 => meta(opcode, "Instruction::Ret", None, None, None, &fixed(16)),
        0xCD => meta(
            opcode,
            "Instruction::Call",
            None,
            Some("Operand16::Imm16".into()),
            None,
            &fixed(24),
        ),
        0xD9 => meta(opcode, "Instruction::Reti", None, None, None, &fixed(16)),
        0xE8 => meta(
            opcode,
            "Instruction::AddSpE8",
            Some("Operand8::SignedImm8".into()),
            None,
            None,
            &fixed(16),
        ),
        0xE9 => meta(opcode, "Instruction::JpHl", None, None, None, &fixed(4)),
        0xE0 => meta(
            opcode,
            "Instruction::LdhImmFromA",
            Some("Operand8::Imm8".into()),
            None,
            None,
            &fixed(12),
        ),
        0xE2 => meta(
            opcode,
            "Instruction::LdhCFromA",
            None,
            None,
            None,
            &fixed(8),
        ),
        0xEA => meta(
            opcode,
            "Instruction::LdImm16FromA",
            None,
            Some("Operand16::Imm16".into()),
            None,
            &fixed(16),
        ),
        0xF8 => meta(
            opcode,
            "Instruction::LdHlSpPlusE8",
            Some("Operand8::SignedImm8".into()),
            None,
            None,
            &fixed(12),
        ),
        0xF9 => meta(opcode, "Instruction::LdSpHl", None, None, None, &fixed(8)),
        0xF0 => meta(
            opcode,
            "Instruction::LdhAFromImm",
            Some("Operand8::Imm8".into()),
            None,
            None,
            &fixed(12),
        ),
        0xF2 => meta(
            opcode,
            "Instruction::LdhAFromC",
            None,
            None,
            None,
            &fixed(8),
        ),
        0xF3 => meta(opcode, "Instruction::Di", None, None, None, &fixed(4)),
        0xFA => meta(
            opcode,
            "Instruction::LdAFromImm16",
            None,
            Some("Operand16::Imm16".into()),
            None,
            &fixed(16),
        ),
        0xFB => meta(opcode, "Instruction::Ei", None, None, None, &fixed(4)),
        _ => return None,
    };
    Some(m)
}

fn cb_metadata_for(opcode: u8) -> String {
    let group = opcode >> 6;
    let register = opcode & 7;
    let bit = (opcode >> 3) & 7;
    let instruction = match group {
        0 => "Instruction::CbRotate",
        1 => "Instruction::CbBit",
        2 => "Instruction::CbRes",
        3 => "Instruction::CbSet",
        _ => unreachable!(),
    };
    let cycles = match group {
        1 => {
            if register == 6 {
                fixed(12)
            } else {
                fixed(8)
            }
        }
        _ => {
            if register == 6 {
                fixed(16)
            } else {
                fixed(8)
            }
        }
    };
    meta(
        opcode,
        instruction,
        Some(r8(register)),
        Some(format!("Operand16::Bit({bit})")),
        None,
        &cycles,
    )
}
